# -*- coding: utf-8 -*-
"""python code1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AjhmkKT8bN-wHVcMcPJQNbZ93Tzai_21
"""

#1.Write a code to get the input in the given format and print the output in the given format.
A = input()
print(','.join(A))

#2.Input:
#A single line contains three float values separated by space.
#2.3 4.5 7.8
#Output:
#Print the float value separated by line.
2.3
4.5
7.8


A = input()
for a in A.split(' '):
    print(a)

#3,The area of an equilateral triangle is ¼(√3a2) where "a" represents a side of the triangle. You are provided with the side "a". Find the area of the equilateral triangle.
a=float(input())
area=0.25*((3**0.5)*(a**2))
print(round(area,2))

#4.You are provided with the radius of a circle "A". Find the length of its circumference.

#Note: In case the output is coming in decimal, roundoff to 2nd decimal place. In case the input is a negative number, print "Error"
a=float(input())
c=2*(22*a)
d=c/7
print(round(d,2))

#5.You will be provided with a number. Print the number of days in the month corresponding to that number.

#Note: In case the input is February, print 28 days. If the Input is not in valid range print "Error".
a = int(input())
b = [1,3,5,7,8,10,12]
c = [4,6,9,11]
d = 2
if a in b:
    print(31)
elif a in c:
    print(30)
elif a == 2:
    print(28)
else:
    print('Error')

